const GROQ_CHAT_URL = 'https://api.groq.com/openai/v1/chat/completions'
const GROQ_TRANSCRIBE_URL = 'https://api.groq.com/openai/v1/audio/transcriptions'

// Injected into every live suggestion system prompt — immune to stale localStorage prompts.
// Prevents hallucination of specifics when transcript context is thin.
const SUGGESTION_RULES =
  '\n\nSUGGESTION INTEGRITY RULES — enforce without exception:\n' +
  '1. NO FABRICATION RULE: Never assert specific numbers, percentages, metrics, timestamps, service names, error codes, database names, technology names, contract terms, SLAs, or any detail not explicitly present in the transcript. Every factual claim in a suggestion must trace directly to a word or phrase actually spoken.\n' +
  '2. CONDITIONAL FRAMING RULE: When the transcript raises a topic but lacks specifics, frame the suggestion as a question to obtain those details — not as a statement of invented facts. Prefer "Ask about...", "Find out...", "Clarify..." over asserting details you do not have.\n' +
  '3. PREVIEW ACCURACY RULE: The preview is the most visible part of each suggestion. A reader must be able to verify every claim in the preview against the transcript. If you cannot point to a specific word or phrase in the transcript to support a claim, remove it from the preview.'

// Injected into every chat/detail system prompt — immune to stale localStorage prompts.
const SYSTEM_RULES =
  '\n\nCORE GUARDRAILS — enforce every rule without exception:\n' +
  '1. INTENT RULE: Identify the user\'s exact intent first. Answer that directly before adding any supporting detail. Do not answer a broader or different question.\n' +
  '2. FOCUS RULE: Stay tightly on topic. Do not introduce side discussions, tangents, or unrelated background unless it directly improves clarity.\n' +
  '3. CONTEXT RULE: Use the provided transcript and meeting context as the primary source of truth. Only use general knowledge when necessary, and clearly label it as such (e.g. "Based on general knowledge…").\n' +
  '4. ACCURACY RULE: Do not invent facts, fill gaps with assumptions, or speculate. If something is unclear, missing, or not in the transcript, state that explicitly.\n' +
  '5. UNCERTAINTY RULE: Clearly distinguish between what is directly stated, what is inferred, and what is unknown. Use phrases like "The transcript states…", "This appears to be…", or "Not specified in the transcript."\n' +
  '6. RELEVANCE RULE: Every sentence must directly support the user\'s request. Remove anything that does not earn its place.\n' +
  '7. DATE RULE: The session metadata block at the top of the context contains the authoritative meeting date and start time — always use it. Never infer the date from model memory, timestamp patterns, or general knowledge. If the metadata block is absent, output "Date: Not specified" — do not guess or fabricate a year.\n' +
  '8. ATTRIBUTION RULE: Do not end responses with "Prepared by", "Generated by", "Prepared from", author signatures, document headers, or closing tags.\n' +
  '9. NO FOLLOW-UP OFFERS RULE: Do not append offers to convert the output into other formats, ask if the user wants more versions, or suggest alternatives at the end of your response. Answer what was asked and stop. If the user wants something else, they will ask.'

type Suggestion = {
  title: string
  preview: string
  intent: string
}

type ChatMessage = {
  role: 'user' | 'assistant'
  content: string
}

const jsonHeaders = (apiKey: string) => ({
  'Content-Type': 'application/json',
  Authorization: `Bearer ${apiKey}`,
})

const extensionFromMime = (mime: string) => {
  if (mime.includes('webm')) return 'webm'
  if (mime.includes('mp4') || mime.includes('m4a')) return 'm4a'
  if (mime.includes('mpeg') || mime.includes('mp3')) return 'mp3'
  if (mime.includes('wav')) return 'wav'
  return 'webm'
}

// Extracts a user-friendly message from a Groq error body.
function parseGroqErrorMessage(status: number, body: string): string {
  try {
    const data = JSON.parse(body) as { error?: { message?: string } }
    const msg = data.error?.message ?? body
    if (status === 429 && (msg.includes('per day') || msg.includes('tokens per day'))) {
      const match = /try again in (.+?)\./i.exec(msg)
      return `Daily token limit reached. Try again in ${match?.[1] ?? 'a few hours'}.`
    }
    return msg.length > 300 ? `${msg.slice(0, 300)}…` : msg
  } catch {
    return body.length > 300 ? `${body.slice(0, 300)}…` : body
  }
}

// Retries on 503 (capacity). For 429, retries only if it's a per-minute limit —
// daily (TPD) 429s are returned immediately since no amount of backoff will clear them.
async function fetchWithRetry(url: string, init: RequestInit): Promise<Response> {
  let response: Response = new Response(null, { status: 500 })
  for (let attempt = 0; attempt < 4; attempt++) {
    if (attempt > 0) {
      await new Promise((r) => setTimeout(r, Math.pow(2, attempt - 1) * 2_000))
    }
    response = await fetch(url, init)
    if (response.ok) return response
    if (response.status === 429) {
      const body = await response.clone().text()
      // TPD (tokens per day) — no retry will help; surface the error immediately.
      if (body.includes('per day') || body.includes('tokens per day')) return response
      // Per-minute rate limit — retry with backoff.
    } else if (response.status !== 503) {
      return response
    }
  }
  return response
}

// Returns only valid suggestions (non-empty title + preview). Never pads with generic fallbacks.
const parseSuggestions = (raw: string): Suggestion[] => {
  try {
    const parsed = JSON.parse(raw) as { suggestions?: unknown[] }
    return (parsed.suggestions ?? [])
      .filter((item): item is Record<string, unknown> => typeof item === 'object' && item !== null)
      .map((item) => ({
        title: String(item.title ?? '').trim(),
        preview: String(item.preview ?? '').trim(),
        intent: String(item.intent ?? 'clarify').trim(),
      }))
      .filter((item) => item.title.length > 0 && item.preview.length > 0)
      .slice(0, 3)
  } catch {
    return []
  }
}

export async function transcribeAudioChunk(apiKey: string, audioBlob: Blob): Promise<string> {
  const mimeType = audioBlob.type || 'audio/webm'
  const extension = extensionFromMime(mimeType)
  const fileName = `chunk-${Date.now()}.${extension}`

  let lastError: Error = new Error('Transcription failed.')

  for (let attempt = 0; attempt < 4; attempt++) {
    if (attempt > 0) {
      await new Promise((r) => setTimeout(r, Math.pow(2, attempt - 1) * 1_000))
    }

    const formData = new FormData()
    formData.append('file', new File([audioBlob], fileName, { type: mimeType }))
    formData.append('model', 'whisper-large-v3')
    formData.append('temperature', '0')
    formData.append('response_format', 'verbose_json')
    formData.append('language', 'en')

    const response = await fetch(GROQ_TRANSCRIBE_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}` },
      body: formData,
    })

    if (response.ok) {
      const data = (await response.json()) as { text?: string }
      return data.text?.trim() ?? ''
    }

    const text = await response.text()
    lastError = new Error(`Transcription failed (${response.status}): ${parseGroqErrorMessage(response.status, text)}`)
    if (response.status !== 503) break
  }

  throw lastError
}

export async function createLiveSuggestions(
  apiKey: string,
  systemPrompt: string,
  transcriptContext: string,
  meetingContext?: string,
  previousTitles?: string[],
): Promise<Suggestion[]> {
  // Novelty hint must stay in system prompt — appending after transcript breaks json_object mode (400).
  const noveltyAddendum = previousTitles?.length
    ? `\n\nAlready shown — do not repeat: ${previousTitles.join(', ')}.`
    : ''
  const effectiveSystem = `${systemPrompt}${noveltyAddendum}${SUGGESTION_RULES}`

  const userContent = meetingContext?.trim()
    ? `Meeting context:\n${meetingContext.trim()}\n\nRecent transcript:\n${transcriptContext}`
    : `Recent transcript context:\n${transcriptContext}`

  const response = await fetchWithRetry(GROQ_CHAT_URL, {
    method: 'POST',
    headers: jsonHeaders(apiKey),
    body: JSON.stringify({
      model: 'openai/gpt-oss-120b',
      temperature: 0.3,
      max_tokens: 700,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: effectiveSystem },
        { role: 'user', content: userContent },
      ],
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    // Any 400 from json_object mode (truncated output, content policy, malformed JSON)
    // is non-critical — skip the batch silently. The timer retries in 30 seconds.
    // Non-400 failures (auth errors, server errors) still surface to the user.
    if (response.status === 400 || body.includes('json_validate_failed') || body.includes('failed_generation')) return []
    throw new Error(`Suggestion request failed: ${parseGroqErrorMessage(response.status, body)}`)
  }

  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }
  const content = data.choices?.[0]?.message?.content
  if (!content) throw new Error('No suggestion content returned from model.')
  return parseSuggestions(content)
}

export async function createDetailedSuggestionAnswer(
  apiKey: string,
  detailPrompt: string,
  transcriptContext: string,
  suggestion: Suggestion,
  meetingContext?: string,
): Promise<string> {
  const contextBlock = meetingContext?.trim()
    ? `Meeting context:\n${meetingContext.trim()}\n\nTranscript context:\n${transcriptContext}`
    : `Transcript context:\n${transcriptContext}`

  const response = await fetchWithRetry(GROQ_CHAT_URL, {
    method: 'POST',
    headers: jsonHeaders(apiKey),
    body: JSON.stringify({
      model: 'openai/gpt-oss-120b',
      temperature: 0.35,
      max_tokens: 2_000,
      messages: [
        { role: 'system', content: `${detailPrompt}${SYSTEM_RULES}` },
        {
          role: 'user',
          content: `${contextBlock}\n\nSelected suggestion:\nTitle: ${suggestion.title}\nPreview: ${suggestion.preview}\nIntent: ${suggestion.intent}`,
        },
      ],
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Suggestion expansion failed: ${parseGroqErrorMessage(response.status, body)}`)
  }
  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }
  return data.choices?.[0]?.message?.content?.trim() || 'No response returned.'
}

export async function createAssistantChatReply(
  apiKey: string,
  chatPrompt: string,
  transcriptContext: string,
  history: Array<{ role: 'user' | 'assistant'; content: string }>,
  meetingContext?: string,
): Promise<string> {
  const contextSection = meetingContext?.trim()
    ? `Meeting context:\n${meetingContext.trim()}\n\nTranscript context:\n${transcriptContext}`
    : `Transcript context:\n${transcriptContext}`

  const trimmedHistory = history.slice(-12).map<ChatMessage>((item) => ({
    role: item.role,
    content: item.content,
  }))

  const response = await fetchWithRetry(GROQ_CHAT_URL, {
    method: 'POST',
    headers: jsonHeaders(apiKey),
    body: JSON.stringify({
      model: 'openai/gpt-oss-120b',
      temperature: 0.35,
      max_tokens: 2_000,
      messages: [
        { role: 'system', content: `${chatPrompt}${SYSTEM_RULES}\n\n${contextSection}` },
        ...trimmedHistory,
      ],
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Chat request failed: ${parseGroqErrorMessage(response.status, body)}`)
  }
  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }
  return data.choices?.[0]?.message?.content?.trim() || 'No response returned.'
}

export function buildExportPayload(input: {
  transcript: unknown[]
  livePreview?: unknown[]
  suggestionBatches: unknown[]
  chatMessages: unknown[]
}) {
  return {
    exportedAt: new Date().toISOString(),
    transcript: input.transcript,
    livePreview: input.livePreview ?? [],
    suggestionBatches: input.suggestionBatches,
    chatHistory: input.chatMessages,
  }
}
