import type { Vibe } from '../types'

export const nowIso = () => new Date().toISOString()
export const makeId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`

export const ATTRIBUTION_RE =
  /^[-*•_\s]*(prepared (by|from|for)|generated by|written by|document prepared|meeting notes prepared|copilot)/i

// Matches unsolicited follow-up offer blocks the model appends unprompted.
export const FOLLOWUP_OFFER_RE =
  /^[-*•\s]*(if you'?d? like|would you like|let me know if|i can also|want me to|shall i|i could also)/i

export const isDailyLimitError = (msg: string) =>
  msg.includes('Daily token limit') || msg.includes('tokens per day')

export const extractWaitTime = (msg: string): string => {
  const m = /try again in (.+?)\.?$/i.exec(msg)
  return m ? ` Try again in ${m[1]}.` : ''
}

export const sanitizeAssistantMarkdown = (raw: string): string => {
  const lines = raw
    .split('\n')
    .filter((line) => !(line.includes('|') && line.split('|').length >= 3))
    .map((line) => (line.trim() === '---' ? '' : line))
    .filter((line) => !ATTRIBUTION_RE.test(line.trim()))

  // Scan from the tail and cut at the first trailing follow-up offer line.
  // Scanning from the end avoids cutting mid-response if the user's own
  // question happened to contain one of these phrases.
  let cutAt = lines.length
  for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i].trim() === '') continue
    if (FOLLOWUP_OFFER_RE.test(lines[i].trim())) { cutAt = i; break }
    break
  }

  return lines
    .slice(0, cutAt)
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

const vibeKeywords: Record<Vibe, string[]> = {
  positive: [
    'congratulations', 'congrats', 'well done', 'good work', 'great job', 'nice work',
    'excellent work', 'outstanding', 'brilliant', 'impressive', 'kudos', 'bravo',
    'nailed it', 'crushed it', 'killed it', 'spot on', 'well said', 'great point',
    'good point', 'love it', 'fantastic', 'amazing', 'awesome', 'superb', 'stellar',
    'shipped', 'launched', 'released', 'deployed', 'delivered', 'completed', 'finished',
    'resolved', 'done', 'approved', 'merged', 'signed off', 'green light', 'on track',
    'great', 'good', 'excellent', 'progress', 'success', 'confident', 'working',
    'agreed', 'absolutely', 'exactly', 'perfect',
  ],
  neutral: [
    'agenda', 'meeting', 'review', 'discussion', 'update', 'consider', 'timeline',
    'roadmap', 'milestone', 'checkpoint', 'follow-up', 'action item', 'next steps',
    'question', 'feedback', 'plan', 'schedule', 'walkthrough', 'overview', 'clarify',
    'presentation', 'handoff', 'sync', 'standup', 'retrospective', 'sprint',
  ],
  critical: [
    'blocked', 'blocker', 'urgent', 'issue', 'bug', 'crash', 'incident', 'risk',
    'delay', 'outage', 'broken', 'error', 'down', 'failed', 'failure', 'critical',
    'problem', 'regression', 'hotfix', 'rollback', 'fix', 'production', 'stuck',
    'concern', 'escalate', 'escalation', 'behind schedule', 'overdue', 'missed',
    'off track', 'red flag', 'showstopper', 'deadline', 'at risk', 'not working',
  ],
}

export const getVibeFromText = (text: string): Vibe => {
  const lower = text.toLowerCase()
  let positive = 0
  let critical = 0
  for (const word of vibeKeywords.positive) if (lower.includes(word)) positive += 1
  for (const word of vibeKeywords.critical) if (lower.includes(word)) critical += 1
  if (critical > 0 && critical >= positive) return 'critical'
  if (positive >= 2) return 'positive'
  return 'neutral'
}

export const pickSupportedMimeType = (): string => {
  const candidates = ['audio/webm;codecs=opus', 'audio/webm', 'audio/mp4']
  for (const candidate of candidates) {
    if (MediaRecorder.isTypeSupported(candidate)) return candidate
  }
  return ''
}

export const buildSessionHeader = (sessionStart: Date | null): string => {
  const d = sessionStart ?? new Date()
  const date = d.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })
  const time = d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
  return `[Session metadata]\nDate: ${date}\nStart time: ${time}\nTimezone: ${tz}\n\n`
}
